[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"
[server]
runOnSave = false
fileWatcherType = "poll"
address = "localhost"
maxUploadSize = 1000  # Size in megabytes